server:
  port: 9000
spring:
  application:
    name: Entre PaginasREST
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/EntrePaginasRESTDB
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org:
      springframework:
        security: DEBUG